apiVersion: v1
kind: Service
metadata:
  name: node-app-service  # Servicio para exponer la app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80  # Puerto externo
      targetPort: 3000  # Puerto interno del container